[package]
name = "rhwid"
description = "Basic HWID Grabbing with encryption support."
version = "0.1.0"
authors = [ "varsity <varsity@duck.com>" ]
edition = "2021"

[lib]
name = "rhwid"
path = "src/lib.rs"

[dependencies]
bitmask-enum = "*"
magic-crypt = "*"
sysinfo = "*"
